name: Deploy to Nairahost

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 82.38.4.100
          username: dalacoee
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/dalacoe.edu.ng/public_html/